volumes:
  ufomt_data:
    external: true

services:
  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - ufomt_data:/var/lib/postgresql/data
    
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    environment:
      DATABASE_URL: postgresql://user:password@db/backend
      WAIT_HOSTS: db:5432
      PORT: 8000
      SIGNING_KEY: mQd1bQ2jIBJv5eOXJOe48moBUxdEJMn30TcYaK5gqGY
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app

  frontend:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    build: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_HOST: http://localhost:8000
